dbt_medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db # Service name in docker-compose
      port: 5432
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: public # Or a dedicated dbt schema
      threads: 4
